<a href="https://colab.research.google.com/github/jaidengoerlitx/Data-Analysis-Projects/blob/main/dataframes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount('/content/drive')
import IPython.display
%cd /content/drive/MyDrive/ColabNotebooks

Mounted at /content/drive
/content/drive/MyDrive/ColabNotebooks

In [ ]:
# import pandas module 
import pandas as pd 
    
# making dataframe 
df1 = pd.read_csv("output_500000.csv") 
   
# output the dataframe
print(df1)

df1.head(1)

         En     id                                              atoms  \
0    7.3580  25020          ['Cl', 'N', 'C', 'C', 'H', 'H', 'H', 'H']
1   11.8509  25059  ['Br', 'Br', 'O', 'N', 'N', 'C', 'C', 'C', 'H'...
2    1.1785  25128  ['F', 'O', 'O', 'N', 'C', 'C', 'H', 'H', 'H', ...
3    4.8583  25188           ['O', 'O', 'C', 'C', 'C', 'H', 'H', 'H']
4    0.0000  25242                               ['F', 'F', 'N', 'H']
..      ...    ...                                                ...
90   6.6401  43581  ['O', 'O', 'O', 'O', 'N', 'C', 'C', 'H', 'H', ...
91   4.5991  43600  ['Br', 'S', 'N', 'N', 'C', 'C', 'C', 'H', 'H',...
92  -1.9294  44250  ['Cl', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'H',...
93   4.4494  45163  ['S', 'O', 'O', 'N', 'C', 'C', 'C', 'H', 'H', ...
94   0.0000  46209                                         ['F', 'O']

                                       coulomb_matrix
0   [4.48794386e+02 6.75320922e+01 3.86237878e+01 ...
1   [2.62735073e+03 3.88055695e+02 7.55471219e+01 ...
2   [97.53309975 26.12731346 14.78373677 15.528918...
3   [73.51669472 28.03244167 20.39715628 37.904755...
4   [97.53309975 35.90425532 45.86740003  4.557077...
..                                                ...
90  [73.51669472 28.16225492 14.95617827 14.826363...
91  [2.62735073e+03 1.77725957e+02 5.98373311e+01 ...
92  [4.48794386e+02 2.30659202e+01 1.97141530e+01 ...
93  [3.88023441e+02 3.29629577e+01 4.34174588e+01 ...
94  [97.53309975 51.04210974 51.04210974 73.51669472]

[95 rows x 4 columns]

,En,id,atoms,coulomb_matrix
0,7.358,25020,"['Cl', 'N', 'C', 'C', 'H', 'H', 'H', 'H']",[4.48794386e+02 6.75320922e+01 3.86237878e+01 ...

In [ ]:

# making dataframe 
df2 = pd.read_csv("output_25000.csv") 
   
# output the dataframe
print(df2)

df2.head(1)

          En     id                                              atoms  \
0     0.3519     11         ['Cl', 'Cl', 'C', 'C', 'H', 'H', 'H', 'H']
1     1.3617     33               ['Cl', 'O', 'C', 'C', 'H', 'H', 'H']
2     0.3991     34     ['Cl', 'O', 'C', 'C', 'H', 'H', 'H', 'H', 'H']
3    10.7891     44  ['O', 'O', 'O', 'O', 'O', 'C', 'C', 'C', 'H', ...
4     2.1242    174  ['O', 'O', 'C', 'C', 'H', 'H', 'H', 'H', 'H', ...
..       ...    ...                                                ...
591   0.0000  24823                                    ['O', 'O', 'O']
592   0.0000  24841                                         ['I', 'H']
593  -0.1416  24845                     ['F', 'F', 'F', 'F', 'N', 'N']
594   0.0000  24855                                         ['I', 'I']
595   0.4044  24883    ['Cl', 'Cl', 'C', 'C', 'C', 'H', 'H', 'H', 'H']

                                        coulomb_matrix
0    [4.48794386e+02 8.74653979e+01 5.72993516e+01 ...
1    [4.48794386e+02 4.66250691e+01 5.77481513e+01 ...
2    [4.48794386e+02 4.45539091e+01 3.74943420e+01 ...
3    [73.51669472 18.24021676 22.39223996 24.520541...
4    [73.51669472 22.8663981  33.74516391 20.050220...
..                                                 ...
591  [73.51669472 44.69215487 51.94797391 44.692154...
592  [6.87435714e+03 3.20837920e+01 3.20837920e+01 ...
593  [97.53309975 35.90372109 29.90432962 29.612048...
594  [6874.35714489 1059.20060332 1059.20060332 687...
595  [4.48794386e+02 5.60786713e+01 5.74106802e+01 ...

[596 rows x 4 columns]

,En,id,atoms,coulomb_matrix
0,0.3519,11,"['Cl', 'Cl', 'C', 'C', 'H', 'H', 'H', 'H']",[4.48794386e+02 8.74653979e+01 5.72993516e+01 ...

In [ ]:

# making dataframe 
df3 = pd.read_csv("output_75000.csv") 
   
# output the dataframe
print(df3)

df3.head(1)

         En     id                               atoms  \
0   -0.1000  55004    ['Br', 'Cl', 'N', 'C', 'C', 'H']
1    0.2725  61108          ['Br', 'F', 'C', 'H', 'H']
2   -0.2433  61169              ['Br', 'Br', 'C', 'C']
3   -0.3747  61170                ['I', 'I', 'C', 'C']
4    0.1183  61280         ['Br', 'Br', 'F', 'C', 'H']
5    0.3869  61330        ['Cl', 'Cl', 'Si', 'H', 'H']
6    0.0001  61437             ['Cl', 'Cl', 'Cl', 'N']
7    2.5530  61526           ['O', 'O', 'O', 'N', 'N']
8    0.0000  61603                ['I', 'I', 'I', 'N']
9    0.0240  61621         ['Br', 'Si', 'H', 'H', 'H']
10   0.1236  61622         ['Cl', 'Si', 'H', 'H', 'H']
11  -2.4297  61681      ['P', 'F', 'F', 'O', 'O', 'H']
12   0.1641  61708               ['Cl', 'N', 'N', 'N']
13   0.0000  61739                         ['Cl', 'O']
14  -0.2360  61744      ['O', 'O', 'N', 'N', 'H', 'H']
15   0.5840  61763                ['I', 'N', 'N', 'N']
16   9.4421  61778      ['S', 'O', 'O', 'O', 'O', 'H']
17   0.0000  61783                     ['S', 'H', 'H']
18  -0.0124  62317                ['O', 'N', 'C', 'H']
19   0.3429  62407          ['Br', 'F', 'F', 'C', 'H']
20  -0.0195  62481                ['S', 'N', 'C', 'H']
21   0.0000  62665                ['P', 'F', 'F', 'F']
22   0.0000  62746                     ['P', 'H', 'H']
23   5.6946  65241           ['P', 'F', 'O', 'O', 'O']
24   2.5834  65357      ['O', 'O', 'O', 'O', 'N', 'H']
25   3.2584  65578    ['Cl', 'Cl', 'O', 'O', 'C', 'C']
26   8.4561  65582    ['Cl', 'Cl', 'O', 'N', 'C', 'H']
27   0.8189  66051      ['O', 'O', 'O', 'C', 'H', 'H']
28   0.0223  66203                ['F', 'O', 'O', 'N']
29   6.9581  66232  ['Br', 'Br', 'Br', 'Br', 'C', 'C']
30   0.0000  66241                         ['Si', 'O']
31   0.0264  66390          ['Si', 'F', 'H', 'H', 'H']
32   0.5274  67630      ['F', 'F', 'F', 'O', 'N', 'C']
33   0.0566  67707        ['Br', 'Br', 'Br', 'F', 'C']
34   0.0011  67708        ['Br', 'Br', 'Cl', 'F', 'C']
35   0.6696  67710      ['F', 'F', 'F', 'N', 'C', 'C']
36   0.8158  67754     ['Br', 'F', 'F', 'C', 'C', 'H']
37   1.2298  67755      ['I', 'F', 'F', 'F', 'C', 'C']
38   0.0722  67897     ['Cl', 'F', 'F', 'N', 'C', 'C']
39   0.6817  67900     ['Cl', 'S', 'F', 'F', 'F', 'C']
40   1.2074  68026     ['Cl', 'F', 'C', 'C', 'H', 'H']
41   2.1428  68048     ['Cl', 'O', 'N', 'C', 'H', 'H']
42  -8.6873  68160      ['S', 'S', 'N', 'N', 'C', 'C']
43   0.0000  68176              ['Br', 'Br', 'S', 'O']
44   0.0004  68407          ['I', 'Br', 'C', 'H', 'H']
45   0.0056  68408          ['I', 'I', 'Br', 'C', 'H']
46  -0.0437  68975               ['Cl', 'C', 'C', 'H']
47   1.0688  68976      ['I', 'C', 'C', 'H', 'H', 'H']
48   0.0337  68982      ['S', 'S', 'S', 'C', 'H', 'H']
49   0.0482  68984       ['Br', 'Br', 'Br', 'Cl', 'C']
50   0.2199  69356      ['I', 'N', 'C', 'C', 'H', 'H']
51   0.0227  69493          ['I', 'I', 'Cl', 'C', 'H']
52   0.0465  70075      ['O', 'N', 'C', 'H', 'H', 'H']
53  11.7121  71081      ['O', 'O', 'O', 'O', 'C', 'C']
54   3.2784  71084   ['Cl', 'Cl', 'Cl', 'F', 'C', 'C']
55   0.6658  71568      ['O', 'C', 'H', 'H', 'H', 'H']
56   0.0021  71583        ['Cl', 'Cl', 'Cl', 'C', 'H']
57   1.5701  73894      ['F', 'F', 'F', 'O', 'C', 'H']
58   0.0000  74596              ['Cl', 'Cl', 'P', 'N']

                                       coulomb_matrix
0   [2.62735073e+03 1.99040764e+02 6.57980525e+01 ...
1   [2.62735073e+03 1.17531102e+02 1.10158595e+02 ...
2   [2627.35073135  252.0600823   112.11114759   6...
3   [6874.35714489  524.91917833  153.18655671   9...
4   [2.62735073e+03 3.90085735e+02 1.17584876e+02 ...
5   [4.48794386e+02 8.85606594e+01 1.16456205e+02 ...
6   [448.79438598  99.9496454   99.93830375  67.58...
7   [73.51669472 28.97426345 25.12521931 45.304691...
8   [6874.35714489  862.37864015  862.41666523  18...
9   [2.62735073e+03 2.25437721e+02 1.16838277e+01 ...
10  [4.48794386e+02 1.16290433e+02 5.91044733e+00 ...
11  [332.34490564  85.95692317  85.96982638  74.22...
12  [448.79438598  68.38965145  47.8121357   34.65...
13  [448.79438598  81.25224041  81.25224041  73.51...
14  [73.51669472 19.56015378 38.70178264 24.701961...
15  [6874.35714489  186.80389783  136.49930139  10...
16  [388.02344103  78.27268499  87.58666234  87.59...
17  [388.02344103  11.93137707  11.93125124  11.93...
18  [73.51669472 39.55081574 18.56220271  8.229986...
19  [2.62735073e+03 1.17417223e+02 1.17413270e+02 ...
20  [388.02344103  40.54738971  60.36976099   4.87...
21  [332.34490564  85.71308224  85.71689497  85.71...
22  [332.34490564  10.60094368  10.60048239  10.60...
23  [332.34490564  84.69788245  78.84474372  78.85...
24  [73.51669472 43.99756353 28.95165164 28.493445...
25  [448.79438598  79.84281319  50.90812638  40.94...
26  [448.79438598  98.78334608  34.99810065  44.43...
27  [73.51669472 44.02075571 28.08603006 35.434432...
28  [97.53309975 32.4963525  32.49645766 45.838181...
29  [2627.35073135  401.99361776  270.5815795   36...
30  [281.62894609  83.93285372  83.93285372  73.51...
31  [281.62894609  78.8189666    9.42757798   9.42...
32  [97.53309975 37.09123227 37.07617972 29.640225...
33  [2627.35073135  391.18321296  391.20983563  11...
34  [2627.35073135  390.72672988  199.15148768  11...
35  [97.53309975 37.03433004 37.03071197 18.865326...
36  [2.62735073e+03 7.81821347e+01 1.03705617e+02 ...
37  [6874.35714489  163.17126179  148.0845192   11...
38  [448.79438598  59.58945052  59.59015671  32.75...
39  [448.79438598 133.81740851  48.4811424   48.36...
40  [4.48794386e+02 3.89280260e+01 5.96108743e+01 ...
41  [448.79438598  51.3858373   45.69698144  58.58...
42  [388.02344103 124.75918193  39.28502423  29.36...
43  [2627.35073135  383.17117506  263.43495644  10...
44  [6.87435714e+03 5.72359748e+02 1.52231328e+02 ...
45  [6.87435714e+03 8.25849390e+02 5.72466418e+02 ...
46  [448.79438598  58.15942515  34.53178956   4.23...
47  [6.87435714e+03 1.55964754e+02 1.06381670e+02 ...
48  [3.88023441e+02 8.68002097e+01 8.50857423e+01 ...
49  [2627.35073135  391.04230255  391.04956833  19...
50  [6.87435714e+03 9.57155459e+01 1.49829859e+02 ...
51  [6.87435714e+03 8.25715029e+02 2.86099611e+02 ...
52  [73.51669472 44.9828558  21.25193083  2.693089...
53  [73.51669472 18.96222517 27.74045263 25.982461...
54  [448.79438598  98.19806385  89.035422    38.73...
55  [73.51669472 33.90309366  3.8882731   3.888539...
56  [448.79438598  99.21869144  99.21898036  57.57...
57  [97.53309975 36.88101609 36.88259006 31.923529...
58  [448.79438598  91.09534995 121.41946696  41.23...

,En,id,atoms,coulomb_matrix
0,-0.1,55004,"['Br', 'Cl', 'N', 'C', 'C', 'H']",[2.62735073e+03 1.99040764e+02 6.57980525e+01 ...

In [ ]:
    
# making dataframe 
df4 = pd.read_csv("output_100000.csv") 
   
# output the dataframe
print(df4)

df4.head(1)

         En     id                                              atoms  \
0    0.8342  75136  ['O', 'O', 'O', 'N', 'C', 'C', 'C', 'H', 'H', ...
1    1.1875  75151  ['S', 'O', 'C', 'C', 'H', 'H', 'H', 'H', 'H', ...
2    4.9936  75161      ['O', 'N', 'N', 'N', 'C', 'C', 'H', 'H', 'H']
3   -0.3311  75205  ['Br', 'Br', 'C', 'C', 'C', 'C', 'H', 'H', 'H'...
4    7.9992  75269  ['O', 'O', 'O', 'C', 'C', 'C', 'H', 'H', 'H', ...
..      ...    ...                                                ...
200  3.9693  98260          ['Cl', 'F', 'O', 'O', 'C', 'C', 'H', 'H']
201  1.4884  98635         ['Cl', 'Cl', 'N', 'N', 'N', 'C', 'C', 'H']
202  3.3590  99295  ['S', 'N', 'C', 'C', 'C', 'H', 'H', 'H', 'H', ...
203  1.1598  99297      ['F', 'N', 'N', 'C', 'C', 'C', 'H', 'H', 'H']
204  1.2927  99484   ['Br', 'Cl', 'Cl', 'N', 'N', 'C', 'C', 'C', 'H']

                                        coulomb_matrix
0    [73.51669472 27.92166335 27.99693091 25.368641...
1    [3.88023441e+02 8.53347820e+01 5.30602139e+01 ...
2    [73.51669472 24.12154563 24.35882259 14.764045...
3    [2.62735073e+03 2.29264041e+02 1.09397449e+02 ...
4    [73.51669472 27.54268325 28.12713067 20.558258...
..                                                 ...
200  [4.48794386e+02 5.98570229e+01 3.53870783e+01 ...
201  [448.79438598  53.92374539  44.82430792  43.77...
202  [3.88023441e+02 3.02238985e+01 5.30824837e+01 ...
203  [97.53309975 26.05499427 17.70845006 40.557690...
204  [2.62735073e+03 1.09051938e+02 1.09188846e+02 ...

[205 rows x 4 columns]

,En,id,atoms,coulomb_matrix
0,0.8342,75136,"['O', 'O', 'O', 'N', 'C', 'C', 'C', 'H', 'H', ...",[73.51669472 27.92166335 27.99693091 25.368641...

In [ ]:
    
# making dataframe 
df5 = pd.read_csv("output_125000.csv") 
   
# output the dataframe
print(df5)

df5.head(1)

         En      id                                              atoms  \
0    0.9603  100698  ['O', 'N', 'C', 'C', 'C', 'C', 'C', 'H', 'H', ...
1    5.9296  100800  ['S', 'O', 'N', 'C', 'C', 'H', 'H', 'H', 'H', ...
2   -0.2536  101392  ['O', 'O', 'O', 'C', 'C', 'C', 'H', 'H', 'H', ...
3    1.3851  101445           ['O', 'N', 'C', 'C', 'C', 'H', 'H', 'H']
4    5.3756  101485         ['Cl', 'Cl', 'N', 'N', 'C', 'C', 'C', 'C']
..      ...     ...                                                ...
162 -3.9516  123554                ['S', 'O', 'C', 'H', 'H', 'H', 'H']
163  3.0138  123582    ['Br', 'Br', 'O', 'C', 'C', 'H', 'H', 'H', 'H']
164  5.1736  123975  ['O', 'O', 'O', 'O', 'O', 'O', 'C', 'C', 'H', ...
165 -0.0555  124984                               ['S', 'O', 'N', 'C']
166 -4.0390  124985                          ['S', 'O', 'N', 'C', 'H']

                                        coulomb_matrix
0    [73.51669472 11.74869242 21.35646803 21.355487...
1    [3.88023441e+02 8.58853637e+01 4.28285818e+01 ...
2    [73.51669472 23.63267194 13.46948597 34.019849...
3    [73.51669472 24.26825951 39.19074169 20.805205...
4    [448.79438598  66.54653945  32.4737457   31.70...
..                                                 ...
162  [3.88023441e+02 7.70296184e+01 5.31810436e+01 ...
163  [2.62735073e+03 3.89494680e+02 8.82449112e+01 ...
164  [73.51669472 18.35155194 27.62784859 24.559555...
165  [388.02344103  77.58200542  39.29537918  56.80...
166  [388.02344103  77.04434591  39.29169186  56.79...

[167 rows x 4 columns]

,En,id,atoms,coulomb_matrix
0,0.9603,100698,"['O', 'N', 'C', 'C', 'C', 'C', 'C', 'H', 'H', ...",[73.51669472 11.74869242 21.35646803 21.355487...

In [ ]:
    
# making dataframe 
df6 = pd.read_csv("output_150000.csv") 
   
# output the dataframe
print(df6)

df6.head(1)

         En      id                                              atoms  \
0    7.4177  126706      ['O', 'O', 'N', 'C', 'C', 'C', 'H', 'H', 'H']
1    0.5167  127602           ['F', 'O', 'O', 'C', 'C', 'H', 'H', 'H']
2    5.8913  128851      ['S', 'O', 'N', 'C', 'C', 'C', 'H', 'H', 'H']
3    1.5635  128857  ['Cl', 'O', 'O', 'C', 'C', 'C', 'C', 'H', 'H',...
4    8.2871  130676  ['S', 'N', 'N', 'N', 'N', 'C', 'C', 'C', 'H', ...
..      ...     ...                                                ...
452  5.9827  148646  ['Br', 'Cl', 'O', 'C', 'C', 'C', 'H', 'H', 'H'...
453  6.0583  149399  ['Cl', 'Cl', 'O', 'C', 'C', 'C', 'H', 'H', 'H'...
454  5.7821  149428  ['Cl', 'O', 'C', 'C', 'C', 'H', 'H', 'H', 'H',...
455  8.1607  149756  ['Cl', 'Cl', 'Cl', 'O', 'C', 'C', 'C', 'H', 'H...
456 -2.5923  149953                         ['Cl', 'O', 'N', 'H', 'H']

                                        coulomb_matrix
0    [73.51669472 14.44141073 23.756409   18.761439...
1    [97.53309975 51.00367932 27.7519204  14.915598...
2    [388.02344103  34.2076462   40.47689582  19.05...
3    [4.48794386e+02 2.48296202e+01 2.34486830e+01 ...
4    [3.88023441e+02 4.37068183e+01 4.37117020e+01 ...
..                                                 ...
452  [2.62735073e+03 1.20622415e+02 8.28216138e+01 ...
453  [4.48794386e+02 6.39099570e+01 4.96504177e+01 ...
454  [4.48794386e+02 3.72135510e+01 3.80545232e+01 ...
455  [4.48794386e+02 8.86233172e+01 7.76490404e+01 ...
456  [4.48794386e+02 5.14097323e+01 6.75802711e+01 ...

[457 rows x 4 columns]

,En,id,atoms,coulomb_matrix
0,7.4177,126706,"['O', 'O', 'N', 'C', 'C', 'C', 'H', 'H', 'H']",[73.51669472 14.44141073 23.756409 18.761439...

In [ ]:
    
# making dataframe 
df7 = pd.read_csv("output_175000.csv") 
   
# output the dataframe
print(df7)

df7.head(1)

          En      id                                              atoms  \
0    -1.0443  150482  ['O', 'N', 'N', 'C', 'C', 'H', 'H', 'H', 'H', ...
1     4.7869  150515           ['I', 'O', 'C', 'C', 'C', 'H', 'H', 'H']
2     5.0689  150516         ['Cl', 'Cl', 'O', 'C', 'C', 'C', 'H', 'H']
3    32.7329  151080  ['C', 'C', 'C', 'C', 'H', 'H', 'H', 'H', 'H', ...
4     8.2631  151137  ['Cl', 'O', 'O', 'O', 'C', 'C', 'C', 'H', 'H',...
..       ...     ...                                                ...
121   2.8350  173032      ['O', 'O', 'O', 'C', 'C', 'H', 'H', 'H', 'H']
122   0.0685  173136                ['S', 'P', 'O', 'O', 'H', 'H', 'H']
123  13.0172  173730      ['O', 'O', 'N', 'N', 'N', 'N', 'N', 'C', 'H']
124   5.9077  174017           ['O', 'O', 'O', 'C', 'C', 'H', 'H', 'H']
125   1.4648  174606                ['O', 'N', 'N', 'C', 'H', 'H', 'H']

                                        coulomb_matrix
0    [73.51669472 25.89568574 40.95773295 13.760638...
1    [6.87435714e+03 1.29617731e+02 1.55887861e+02 ...
2    [4.48794386e+02 8.76079895e+01 4.54584419e+01 ...
3    [36.8581052  25.18054498 25.18070292 13.307283...
4    [4.48794386e+02 2.71731829e+01 4.65419088e+01 ...
..                                                 ...
121  [73.51669472 27.11236194 17.4907505  34.801724...
122  [3.88023441e+02 1.13973748e+02 4.51895009e+01 ...
123  [73.51669472 29.15368717 44.17334414 15.896198...
124  [73.51669472 27.39675694 44.46663473 20.567983...
125  [73.51669472 25.90124975 40.95561338 13.760271...

[126 rows x 4 columns]

,En,id,atoms,coulomb_matrix
0,-1.0443,150482,"['O', 'N', 'N', 'C', 'C', 'H', 'H', 'H', 'H', ...",[73.51669472 25.89568574 40.95773295 13.760638...

In [ ]:
    
# making dataframe 
df8 = pd.read_csv("output_200000.csv") 
   
# output the dataframe
print(df8)

df8.head(1)

         En      id                                              atoms  \
0   15.2412  177047                          ['S', 'S', 'P', 'O', 'O']
1    3.9060  177062      ['I', 'I', 'I', 'S', 'C', 'C', 'C', 'C', 'H']
2    1.5091  177069  ['O', 'O', 'N', 'C', 'C', 'H', 'H', 'H', 'H', ...
3   21.1687  177159  ['Cl', 'Cl', 'Cl', 'Cl', 'Cl', 'C', 'C', 'C', ...
4    0.0000  177447                                    ['S', 'H', 'H']
..      ...     ...                                                ...
76 -15.3564  197063  ['S', 'P', 'O', 'O', 'C', 'H', 'H', 'H', 'H', ...
77   1.3155  197765                         ['Cl', 'S', 'P', 'F', 'F']
78  -0.1303  197839  ['N', 'N', 'N', 'N', 'H', 'H', 'H', 'H', 'H', ...
79   2.3983  198669           ['O', 'N', 'N', 'C', 'H', 'H', 'H', 'H']
80   1.4648  198676                ['O', 'N', 'N', 'C', 'H', 'H', 'H']

                                       coulomb_matrix
0   [388.02344103  85.03002756 120.59296359  43.89...
1   [6.87435714e+03 7.18206213e+02 4.57323453e+02 ...
2   [73.51669472 27.58504881 38.50692911 20.543019...
3   [448.79438598  92.76595517  90.15572498  66.46...
4   [388.02344103  11.93137707  11.93125124  11.93...
..                                                ...
76  [3.88023441e+02 1.23936587e+02 4.23308966e+01 ...
77  [448.79438598  84.20286972 126.86899406  52.01...
78  [53.3587074  34.49074203 34.48162638 20.975128...
79  [73.51669472 26.93767653 45.33345004 14.377344...
80  [73.51669472 25.90124975 40.95561338 13.760271...

[81 rows x 4 columns]

,En,id,atoms,coulomb_matrix
0,15.2412,177047,"['S', 'S', 'P', 'O', 'O']",[388.02344103 85.03002756 120.59296359 43.89...

In [ ]:
    
# making dataframe 
df9 = pd.read_csv("output_225000.csv") 
   
# output the dataframe
print(df9)

df9.head(1)

        En      id                                              atoms  \
0   1.2057  200605    ['Br', 'Br', 'N', 'N', 'C', 'C', 'C', 'H', 'H']
1  12.9264  201315  ['S', 'N', 'N', 'N', 'C', 'C', 'C', 'H', 'H', ...
2   0.0000  204018                             ['Cl', 'Cl', 'P', 'F']
3   2.9449  204804    ['Br', 'Br', 'S', 'C', 'C', 'H', 'H', 'H', 'H']
4  12.7362  206611     ['Cl', 'O', 'O', 'N', 'N', 'C', 'H', 'H', 'H']
5  17.1821  211207                ['P', 'O', 'O', 'O', 'N', 'H', 'H']
6   9.4453  219616  ['Br', 'Br', 'Br', 'O', 'N', 'C', 'C', 'C', 'H...
7  12.1476  222465      ['O', 'O', 'C', 'C', 'C', 'H', 'H', 'H', 'H']
8   2.4486  222700    ['Cl', 'Cl', 'F', 'F', 'C', 'C', 'C', 'H', 'H']
9   3.6703  224991  ['Cl', 'Cl', 'Cl', 'Cl', 'S', 'C', 'C', 'H', 'H']

                                      coulomb_matrix
0  [2.62735073e+03 3.39976081e+02 8.56762890e+01 ...
1  [388.02344103  41.38947465  29.95583206  41.29...
2  [448.79438598  91.10396457 121.4331952   54.70...
3  [2.62735073e+03 2.06603729e+02 1.85776429e+02 ...
4  [448.79438598  35.70641357  49.02870464  67.35...
5  [332.34490564  78.6811742   78.68482021  78.65...
6  [2.62735073e+03 3.89557239e+02 3.90849446e+02 ...
7  [73.51669472 27.41962511 35.11058811 20.031330...
8  [448.79438598  86.70042277  31.71245169  36.76...
9  [448.79438598  98.88956846  99.78287905  58.23...

,En,id,atoms,coulomb_matrix
0,1.2057,200605,"['Br', 'Br', 'N', 'N', 'C', 'C', 'C', 'H', 'H']",[2.62735073e+03 3.39976081e+02 8.56762890e+01 ...

In [ ]:
    
# making dataframe 
df10 = pd.read_csv("output_250000.csv") 
   
# output the dataframe
print(df10)

df10.head(1)

         En      id                                              atoms  \
0   10.8290  225029  ['N', 'N', 'N', 'N', 'C', 'C', 'H', 'H', 'H', ...
1   27.8346  225958  ['Cl', 'Cl', 'Cl', 'Cl', 'Cl', 'O', 'C', 'C', ...
2    2.8041  227927  ['O', 'N', 'N', 'N', 'C', 'C', 'C', 'H', 'H', ...
3    4.4892  228231  ['S', 'S', 'O', 'O', 'C', 'C', 'H', 'H', 'H', ...
4    2.6134  228396  ['Cl', 'F', 'O', 'C', 'C', 'C', 'H', 'H', 'H',...
5    0.3592  228397  ['F', 'F', 'O', 'C', 'C', 'C', 'H', 'H', 'H', ...
6   13.0328  229071           ['O', 'N', 'N', 'N', 'C', 'C', 'C', 'H']
7   -3.0854  230911           ['S', 'S', 'S', 'S', 'S', 'S', 'C', 'C']
8    3.8118  231273  ['Cl', 'Cl', 'O', 'C', 'C', 'C', 'H', 'H', 'H'...
9   10.5252  234322  ['F', 'F', 'O', 'O', 'O', 'O', 'N', 'C', 'C', ...
10   2.5326  235121    ['Br', 'Cl', 'C', 'C', 'C', 'H', 'H', 'H', 'H']
11  15.3221  237259  ['Cl', 'Cl', 'Cl', 'N', 'N', 'C', 'C', 'C', 'C...
12   9.7591  238417  ['Cl', 'Cl', 'Cl', 'Cl', 'F', 'F', 'O', 'C', '...
13  -0.9928  239041      ['N', 'C', 'C', 'C', 'H', 'H', 'H', 'H', 'H']
14   6.0191  239101      ['S', 'S', 'N', 'N', 'C', 'C', 'C', 'H', 'H']
15   3.1125  239787      ['O', 'N', 'N', 'N', 'C', 'C', 'H', 'H', 'H']
16   6.9479  243659  ['Cl', 'Cl', 'Cl', 'Cl', 'F', 'F', 'C', 'C', 'C']
17   4.1003  244725           ['S', 'N', 'N', 'N', 'N', 'C', 'H', 'H']
18   4.1919  245975  ['N', 'N', 'N', 'N', 'C', 'C', 'H', 'H', 'H', ...
19   1.1209  247762                  ['Cl', 'Cl', 'Cl', 'S', 'C', 'H']
20   2.5921  248238  ['Cl', 'S', 'O', 'N', 'C', 'C', 'H', 'H', 'H',...
21  14.3931  248852  ['Br', 'Br', 'N', 'N', 'C', 'C', 'C', 'C', 'H'...
22  17.2527  249007  ['Cl', 'Cl', 'Cl', 'N', 'N', 'C', 'C', 'C', 'C...

                                       coulomb_matrix
0   [53.3587074  25.7462271  20.01474721 19.870986...
1   [448.79438598  99.95771556  98.31193915  61.21...
2   [73.51669472 12.65712539 15.7224761  13.052149...
3   [3.88023441e+02 1.24960807e+02 4.63137263e+01 ...
4   [4.48794386e+02 3.02060839e+01 4.70826347e+01 ...
5   [97.53309975 17.1250821  27.15187269 22.831035...
6   [73.51669472 40.02549272 11.83304698 18.308201...
7   [388.02344103 124.22016161  86.63575746  71.06...
8   [4.48794386e+02 9.81209993e+01 2.79016965e+01 ...
9   [97.53309975 36.96789384 27.10804745 20.522388...
10  [2.62735073e+03 1.58711374e+02 1.09429126e+02 ...
11  [448.79438598  88.08751444  47.31357724  29.73...
12  [448.79438598  98.99949808  63.72217041  59.58...
13  [53.3587074  28.82079833 17.44029234 12.110589...
14  [388.02344103  35.35179174  40.48086659  22.38...
15  [73.51669472 25.0314276  24.28870079 25.032695...
16  [448.79438598  79.31100258  57.46130272  74.31...
17  [388.02344103  41.67889407  44.29991976  66.66...
18  [53.3587074  20.96726049 21.56446643 20.796082...
19  [448.79438598  99.49344241  85.97826112  91.70...
20  [4.48794386e+02 6.02127035e+01 2.58338659e+01 ...
21  [2.62735073e+03 1.94928231e+02 8.89690649e+01 ...
22  [448.79438598  89.02048365  89.02176319  29.80...

,En,id,atoms,coulomb_matrix
0,10.829,225029,"['N', 'N', 'N', 'N', 'C', 'C', 'H', 'H', 'H', ...",[53.3587074 25.7462271 20.01474721 19.870986...

In [ ]:
new_df1 = pd.concat([df1, df2], ignore_index=True)
print(new_df1)
last_row = new_df1.iloc[-1:]

#view last row
#print(last_row), axis=0, join= 'outer')
#print(new_df1)

          En     id                                              atoms  \
0     7.3580  25020          ['Cl', 'N', 'C', 'C', 'H', 'H', 'H', 'H']
1    11.8509  25059  ['Br', 'Br', 'O', 'N', 'N', 'C', 'C', 'C', 'H'...
2     1.1785  25128  ['F', 'O', 'O', 'N', 'C', 'C', 'H', 'H', 'H', ...
3     4.8583  25188           ['O', 'O', 'C', 'C', 'C', 'H', 'H', 'H']
4     0.0000  25242                               ['F', 'F', 'N', 'H']
..       ...    ...                                                ...
686   0.0000  24823                                    ['O', 'O', 'O']
687   0.0000  24841                                         ['I', 'H']
688  -0.1416  24845                     ['F', 'F', 'F', 'F', 'N', 'N']
689   0.0000  24855                                         ['I', 'I']
690   0.4044  24883    ['Cl', 'Cl', 'C', 'C', 'C', 'H', 'H', 'H', 'H']

                                        coulomb_matrix
0    [4.48794386e+02 6.75320922e+01 3.86237878e+01 ...
1    [2.62735073e+03 3.88055695e+02 7.55471219e+01 ...
2    [97.53309975 26.12731346 14.78373677 15.528918...
3    [73.51669472 28.03244167 20.39715628 37.904755...
4    [97.53309975 35.90425532 45.86740003  4.557077...
..                                                 ...
686  [73.51669472 44.69215487 51.94797391 44.692154...
687  [6.87435714e+03 3.20837920e+01 3.20837920e+01 ...
688  [97.53309975 35.90372109 29.90432962 29.612048...
689  [6874.35714489 1059.20060332 1059.20060332 687...
690  [4.48794386e+02 5.60786713e+01 5.74106802e+01 ...

[691 rows x 4 columns]

In [ ]:
new_df2 = pd.concat([new_df1, df3], ignore_index=True)
print(new_df2)
last_row = new_df1.iloc[-1:]

#view last row
#print(last_row), axis=0, join= 'outer')
#print(new_df1)

          En     id                                              atoms  \
0     7.3580  25020          ['Cl', 'N', 'C', 'C', 'H', 'H', 'H', 'H']
1    11.8509  25059  ['Br', 'Br', 'O', 'N', 'N', 'C', 'C', 'C', 'H'...
2     1.1785  25128  ['F', 'O', 'O', 'N', 'C', 'C', 'H', 'H', 'H', ...
3     4.8583  25188           ['O', 'O', 'C', 'C', 'C', 'H', 'H', 'H']
4     0.0000  25242                               ['F', 'F', 'N', 'H']
..       ...    ...                                                ...
745   3.2784  71084                  ['Cl', 'Cl', 'Cl', 'F', 'C', 'C']
746   0.6658  71568                     ['O', 'C', 'H', 'H', 'H', 'H']
747   0.0021  71583                       ['Cl', 'Cl', 'Cl', 'C', 'H']
748   1.5701  73894                     ['F', 'F', 'F', 'O', 'C', 'H']
749   0.0000  74596                             ['Cl', 'Cl', 'P', 'N']

                                        coulomb_matrix
0    [4.48794386e+02 6.75320922e+01 3.86237878e+01 ...
1    [2.62735073e+03 3.88055695e+02 7.55471219e+01 ...
2    [97.53309975 26.12731346 14.78373677 15.528918...
3    [73.51669472 28.03244167 20.39715628 37.904755...
4    [97.53309975 35.90425532 45.86740003  4.557077...
..                                                 ...
745  [448.79438598  98.19806385  89.035422    38.73...
746  [73.51669472 33.90309366  3.8882731   3.888539...
747  [448.79438598  99.21869144  99.21898036  57.57...
748  [97.53309975 36.88101609 36.88259006 31.923529...
749  [448.79438598  91.09534995 121.41946696  41.23...

[750 rows x 4 columns]

In [ ]:
new_df3 = pd.concat([new_df2, df4], ignore_index=True)
print(new_df3)
last_row = new_df1.iloc[-1:]

#view last row
#print(last_row), axis=0, join= 'outer')
#print(new_df1)

          En     id                                              atoms  \
0     7.3580  25020          ['Cl', 'N', 'C', 'C', 'H', 'H', 'H', 'H']
1    11.8509  25059  ['Br', 'Br', 'O', 'N', 'N', 'C', 'C', 'C', 'H'...
2     1.1785  25128  ['F', 'O', 'O', 'N', 'C', 'C', 'H', 'H', 'H', ...
3     4.8583  25188           ['O', 'O', 'C', 'C', 'C', 'H', 'H', 'H']
4     0.0000  25242                               ['F', 'F', 'N', 'H']
..       ...    ...                                                ...
950   3.9693  98260          ['Cl', 'F', 'O', 'O', 'C', 'C', 'H', 'H']
951   1.4884  98635         ['Cl', 'Cl', 'N', 'N', 'N', 'C', 'C', 'H']
952   3.3590  99295  ['S', 'N', 'C', 'C', 'C', 'H', 'H', 'H', 'H', ...
953   1.1598  99297      ['F', 'N', 'N', 'C', 'C', 'C', 'H', 'H', 'H']
954   1.2927  99484   ['Br', 'Cl', 'Cl', 'N', 'N', 'C', 'C', 'C', 'H']

                                        coulomb_matrix
0    [4.48794386e+02 6.75320922e+01 3.86237878e+01 ...
1    [2.62735073e+03 3.88055695e+02 7.55471219e+01 ...
2    [97.53309975 26.12731346 14.78373677 15.528918...
3    [73.51669472 28.03244167 20.39715628 37.904755...
4    [97.53309975 35.90425532 45.86740003  4.557077...
..                                                 ...
950  [4.48794386e+02 5.98570229e+01 3.53870783e+01 ...
951  [448.79438598  53.92374539  44.82430792  43.77...
952  [3.88023441e+02 3.02238985e+01 5.30824837e+01 ...
953  [97.53309975 26.05499427 17.70845006 40.557690...
954  [2.62735073e+03 1.09051938e+02 1.09188846e+02 ...

[955 rows x 4 columns]

In [ ]:
new_df4 = pd.concat([new_df3, df5], ignore_index=True)
print(new_df4)
last_row = new_df1.iloc[-1:]

#view last row
#print(last_row), axis=0, join= 'outer')
#print(new_df1)

           En      id                                              atoms  \
0      7.3580   25020          ['Cl', 'N', 'C', 'C', 'H', 'H', 'H', 'H']
1     11.8509   25059  ['Br', 'Br', 'O', 'N', 'N', 'C', 'C', 'C', 'H'...
2      1.1785   25128  ['F', 'O', 'O', 'N', 'C', 'C', 'H', 'H', 'H', ...
3      4.8583   25188           ['O', 'O', 'C', 'C', 'C', 'H', 'H', 'H']
4      0.0000   25242                               ['F', 'F', 'N', 'H']
...       ...     ...                                                ...
1117  -3.9516  123554                ['S', 'O', 'C', 'H', 'H', 'H', 'H']
1118   3.0138  123582    ['Br', 'Br', 'O', 'C', 'C', 'H', 'H', 'H', 'H']
1119   5.1736  123975  ['O', 'O', 'O', 'O', 'O', 'O', 'C', 'C', 'H', ...
1120  -0.0555  124984                               ['S', 'O', 'N', 'C']
1121  -4.0390  124985                          ['S', 'O', 'N', 'C', 'H']

                                         coulomb_matrix
0     [4.48794386e+02 6.75320922e+01 3.86237878e+01 ...
1     [2.62735073e+03 3.88055695e+02 7.55471219e+01 ...
2     [97.53309975 26.12731346 14.78373677 15.528918...
3     [73.51669472 28.03244167 20.39715628 37.904755...
4     [97.53309975 35.90425532 45.86740003  4.557077...
...                                                 ...
1117  [3.88023441e+02 7.70296184e+01 5.31810436e+01 ...
1118  [2.62735073e+03 3.89494680e+02 8.82449112e+01 ...
1119  [73.51669472 18.35155194 27.62784859 24.559555...
1120  [388.02344103  77.58200542  39.29537918  56.80...
1121  [388.02344103  77.04434591  39.29169186  56.79...

[1122 rows x 4 columns]

In [ ]:
new_df5 = pd.concat([new_df4, df6], ignore_index=True)
print(new_df5)
last_row = new_df1.iloc[-1:]

#view last row
#print(last_row), axis=0, join= 'outer')
#print(new_df1)

           En      id                                              atoms  \
0      7.3580   25020          ['Cl', 'N', 'C', 'C', 'H', 'H', 'H', 'H']
1     11.8509   25059  ['Br', 'Br', 'O', 'N', 'N', 'C', 'C', 'C', 'H'...
2      1.1785   25128  ['F', 'O', 'O', 'N', 'C', 'C', 'H', 'H', 'H', ...
3      4.8583   25188           ['O', 'O', 'C', 'C', 'C', 'H', 'H', 'H']
4      0.0000   25242                               ['F', 'F', 'N', 'H']
...       ...     ...                                                ...
1574   5.9827  148646  ['Br', 'Cl', 'O', 'C', 'C', 'C', 'H', 'H', 'H'...
1575   6.0583  149399  ['Cl', 'Cl', 'O', 'C', 'C', 'C', 'H', 'H', 'H'...
1576   5.7821  149428  ['Cl', 'O', 'C', 'C', 'C', 'H', 'H', 'H', 'H',...
1577   8.1607  149756  ['Cl', 'Cl', 'Cl', 'O', 'C', 'C', 'C', 'H', 'H...
1578  -2.5923  149953                         ['Cl', 'O', 'N', 'H', 'H']

                                         coulomb_matrix
0     [4.48794386e+02 6.75320922e+01 3.86237878e+01 ...
1     [2.62735073e+03 3.88055695e+02 7.55471219e+01 ...
2     [97.53309975 26.12731346 14.78373677 15.528918...
3     [73.51669472 28.03244167 20.39715628 37.904755...
4     [97.53309975 35.90425532 45.86740003  4.557077...
...                                                 ...
1574  [2.62735073e+03 1.20622415e+02 8.28216138e+01 ...
1575  [4.48794386e+02 6.39099570e+01 4.96504177e+01 ...
1576  [4.48794386e+02 3.72135510e+01 3.80545232e+01 ...
1577  [4.48794386e+02 8.86233172e+01 7.76490404e+01 ...
1578  [4.48794386e+02 5.14097323e+01 6.75802711e+01 ...

[1579 rows x 4 columns]

In [ ]:
new_df6 = pd.concat([new_df5, df7], ignore_index=True)
print(new_df6)
last_row = new_df1.iloc[-1:]

#view last row
#print(last_row), axis=0, join= 'outer')
#print(new_df1)

           En      id                                              atoms  \
0      7.3580   25020          ['Cl', 'N', 'C', 'C', 'H', 'H', 'H', 'H']
1     11.8509   25059  ['Br', 'Br', 'O', 'N', 'N', 'C', 'C', 'C', 'H'...
2      1.1785   25128  ['F', 'O', 'O', 'N', 'C', 'C', 'H', 'H', 'H', ...
3      4.8583   25188           ['O', 'O', 'C', 'C', 'C', 'H', 'H', 'H']
4      0.0000   25242                               ['F', 'F', 'N', 'H']
...       ...     ...                                                ...
1700   2.8350  173032      ['O', 'O', 'O', 'C', 'C', 'H', 'H', 'H', 'H']
1701   0.0685  173136                ['S', 'P', 'O', 'O', 'H', 'H', 'H']
1702  13.0172  173730      ['O', 'O', 'N', 'N', 'N', 'N', 'N', 'C', 'H']
1703   5.9077  174017           ['O', 'O', 'O', 'C', 'C', 'H', 'H', 'H']
1704   1.4648  174606                ['O', 'N', 'N', 'C', 'H', 'H', 'H']

                                         coulomb_matrix
0     [4.48794386e+02 6.75320922e+01 3.86237878e+01 ...
1     [2.62735073e+03 3.88055695e+02 7.55471219e+01 ...
2     [97.53309975 26.12731346 14.78373677 15.528918...
3     [73.51669472 28.03244167 20.39715628 37.904755...
4     [97.53309975 35.90425532 45.86740003  4.557077...
...                                                 ...
1700  [73.51669472 27.11236194 17.4907505  34.801724...
1701  [3.88023441e+02 1.13973748e+02 4.51895009e+01 ...
1702  [73.51669472 29.15368717 44.17334414 15.896198...
1703  [73.51669472 27.39675694 44.46663473 20.567983...
1704  [73.51669472 25.90124975 40.95561338 13.760271...

[1705 rows x 4 columns]

In [ ]:
new_df7 = pd.concat([new_df6, df8], ignore_index=True)
print(new_df7)
last_row = new_df1.iloc[-1:]

#view last row
#print(last_row), axis=0, join= 'outer')
#print(new_df1)

           En      id                                              atoms  \
0      7.3580   25020          ['Cl', 'N', 'C', 'C', 'H', 'H', 'H', 'H']
1     11.8509   25059  ['Br', 'Br', 'O', 'N', 'N', 'C', 'C', 'C', 'H'...
2      1.1785   25128  ['F', 'O', 'O', 'N', 'C', 'C', 'H', 'H', 'H', ...
3      4.8583   25188           ['O', 'O', 'C', 'C', 'C', 'H', 'H', 'H']
4      0.0000   25242                               ['F', 'F', 'N', 'H']
...       ...     ...                                                ...
1781 -15.3564  197063  ['S', 'P', 'O', 'O', 'C', 'H', 'H', 'H', 'H', ...
1782   1.3155  197765                         ['Cl', 'S', 'P', 'F', 'F']
1783  -0.1303  197839  ['N', 'N', 'N', 'N', 'H', 'H', 'H', 'H', 'H', ...
1784   2.3983  198669           ['O', 'N', 'N', 'C', 'H', 'H', 'H', 'H']
1785   1.4648  198676                ['O', 'N', 'N', 'C', 'H', 'H', 'H']

                                         coulomb_matrix
0     [4.48794386e+02 6.75320922e+01 3.86237878e+01 ...
1     [2.62735073e+03 3.88055695e+02 7.55471219e+01 ...
2     [97.53309975 26.12731346 14.78373677 15.528918...
3     [73.51669472 28.03244167 20.39715628 37.904755...
4     [97.53309975 35.90425532 45.86740003  4.557077...
...                                                 ...
1781  [3.88023441e+02 1.23936587e+02 4.23308966e+01 ...
1782  [448.79438598  84.20286972 126.86899406  52.01...
1783  [53.3587074  34.49074203 34.48162638 20.975128...
1784  [73.51669472 26.93767653 45.33345004 14.377344...
1785  [73.51669472 25.90124975 40.95561338 13.760271...

[1786 rows x 4 columns]

In [ ]:
new_df8 = pd.concat([new_df7, df9], ignore_index=True)
print(new_df8)
last_row = new_df1.iloc[-1:]

#view last row
#print(last_row), axis=0, join= 'outer')
#print(new_df1)

           En      id                                              atoms  \
0      7.3580   25020          ['Cl', 'N', 'C', 'C', 'H', 'H', 'H', 'H']
1     11.8509   25059  ['Br', 'Br', 'O', 'N', 'N', 'C', 'C', 'C', 'H'...
2      1.1785   25128  ['F', 'O', 'O', 'N', 'C', 'C', 'H', 'H', 'H', ...
3      4.8583   25188           ['O', 'O', 'C', 'C', 'C', 'H', 'H', 'H']
4      0.0000   25242                               ['F', 'F', 'N', 'H']
...       ...     ...                                                ...
1791  17.1821  211207                ['P', 'O', 'O', 'O', 'N', 'H', 'H']
1792   9.4453  219616  ['Br', 'Br', 'Br', 'O', 'N', 'C', 'C', 'C', 'H...
1793  12.1476  222465      ['O', 'O', 'C', 'C', 'C', 'H', 'H', 'H', 'H']
1794   2.4486  222700    ['Cl', 'Cl', 'F', 'F', 'C', 'C', 'C', 'H', 'H']
1795   3.6703  224991  ['Cl', 'Cl', 'Cl', 'Cl', 'S', 'C', 'C', 'H', 'H']

                                         coulomb_matrix
0     [4.48794386e+02 6.75320922e+01 3.86237878e+01 ...
1     [2.62735073e+03 3.88055695e+02 7.55471219e+01 ...
2     [97.53309975 26.12731346 14.78373677 15.528918...
3     [73.51669472 28.03244167 20.39715628 37.904755...
4     [97.53309975 35.90425532 45.86740003  4.557077...
...                                                 ...
1791  [332.34490564  78.6811742   78.68482021  78.65...
1792  [2.62735073e+03 3.89557239e+02 3.90849446e+02 ...
1793  [73.51669472 27.41962511 35.11058811 20.031330...
1794  [448.79438598  86.70042277  31.71245169  36.76...
1795  [448.79438598  98.88956846  99.78287905  58.23...

[1796 rows x 4 columns]

## This is the final Dataframe !!

In [ ]:
new_df9 = pd.concat([new_df8, df10], ignore_index=True)
print(new_df9)
last_row = new_df1.iloc[-1:]

#view last row
#print(last_row), axis=0, join= 'outer')
#print(new_df1)

           En      id                                              atoms  \
0      7.3580   25020          ['Cl', 'N', 'C', 'C', 'H', 'H', 'H', 'H']
1     11.8509   25059  ['Br', 'Br', 'O', 'N', 'N', 'C', 'C', 'C', 'H'...
2      1.1785   25128  ['F', 'O', 'O', 'N', 'C', 'C', 'H', 'H', 'H', ...
3      4.8583   25188           ['O', 'O', 'C', 'C', 'C', 'H', 'H', 'H']
4      0.0000   25242                               ['F', 'F', 'N', 'H']
...       ...     ...                                                ...
1814   4.1919  245975  ['N', 'N', 'N', 'N', 'C', 'C', 'H', 'H', 'H', ...
1815   1.1209  247762                  ['Cl', 'Cl', 'Cl', 'S', 'C', 'H']
1816   2.5921  248238  ['Cl', 'S', 'O', 'N', 'C', 'C', 'H', 'H', 'H',...
1817  14.3931  248852  ['Br', 'Br', 'N', 'N', 'C', 'C', 'C', 'C', 'H'...
1818  17.2527  249007  ['Cl', 'Cl', 'Cl', 'N', 'N', 'C', 'C', 'C', 'C...

                                         coulomb_matrix
0     [4.48794386e+02 6.75320922e+01 3.86237878e+01 ...
1     [2.62735073e+03 3.88055695e+02 7.55471219e+01 ...
2     [97.53309975 26.12731346 14.78373677 15.528918...
3     [73.51669472 28.03244167 20.39715628 37.904755...
4     [97.53309975 35.90425532 45.86740003  4.557077...
...                                                 ...
1814  [53.3587074  20.96726049 21.56446643 20.796082...
1815  [448.79438598  99.49344241  85.97826112  91.70...
1816  [4.48794386e+02 6.02127035e+01 2.58338659e+01 ...
1817  [2.62735073e+03 1.94928231e+02 8.89690649e+01 ...
1818  [448.79438598  89.02048365  89.02176319  29.80...

[1819 rows x 4 columns]

In [ ]:
# assume df is your dataframe with a "coulomb_matrix" column containing lists
# use apply() with len() to get the length of each list in the "coulomb_matrix" column
coulomb_matrix_lengths = new_df9["coulomb_matrix"].apply(len)
print(coulomb_matrix_lengths)

# this will create a new Series containing the length of each list in the "coulomb_matrix" column
# you can then use this Series however you want, for example to calculate summary statistics or to plot a histogram

0        976
1       1525
2       1209
3        779
4        194
        ...
1814    1208
1815     474
1816    1525
1817    1525
1818    1317
Name: coulomb_matrix, Length: 1819, dtype: int64